export const AppRoutes = {
  home: "/",
  login: "/login",
  dashboard: '/dashboard',
  users: "/users",
  admins: "/admins",
  addUser: "/adduser",
  manageAd: "/manageAd",
  profile: "/profile",
  statusMaster: "/masters/statusMaster",
  categoryMaster: "/masters/categoryMaster",
  kulamMaster: '/kulamMaster',
  roleMaster: '/roleMaster',
  masters: "/masters",
  post: "/post",
  userProfileList: "/userslist",
  support: "/support",
  announcement: "/announcement",
  updateprofile: "/updateprofile",
  changepassword: "/changepassword",
  addannouncement: "/addannouncement"
};
